# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0008_auto_20170612_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex1set1',
            new_name='ex1set1t1',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex1set2',
            new_name='ex1set1t2',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex1set3',
            new_name='ex1set1t3',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex2set1',
            new_name='ex1set2t1',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex2set2',
            new_name='ex1set2t2',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex2set3',
            new_name='ex1set2t3',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex3set1',
            new_name='ex1set3t1',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex3set2',
            new_name='ex1set3t2',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex3set3',
            new_name='ex1set3t3',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex4set1',
            new_name='ex2set1t1',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex4set2',
            new_name='ex2set1t2',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex4set3',
            new_name='ex2set1t3',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex5set1',
            new_name='ex2set2t1',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex5set2',
            new_name='ex2set2t2',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex5set3',
            new_name='ex2set2t3',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex6set1',
            new_name='ex2set3t1',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex6set2',
            new_name='ex2set3t2',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex6set3',
            new_name='ex2set3t3',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex7set1',
            new_name='ex3set1t1',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex7set2',
            new_name='ex3set1t2',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex7set3',
            new_name='ex3set1t3',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex8set1',
            new_name='ex3set2t1',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex8set2',
            new_name='ex3set2t2',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex8set3',
            new_name='ex3set2t3',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex9set1',
            new_name='ex3set3t1',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex9set2',
            new_name='ex3set3t2',
        ),
        migrations.RenameField(
            model_name='daystage1',
            old_name='ex9set3',
            new_name='ex3set3t3',
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex4set1t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex4set1t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex4set1t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex4set2t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex4set2t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex4set2t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex4set3t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex4set3t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex4set3t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex5set1t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex5set1t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex5set1t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex5set2t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex5set2t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex5set2t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex5set3t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex5set3t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex5set3t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex6set1t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex6set1t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex6set1t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex6set2t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex6set2t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex6set2t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex6set3t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex6set3t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex6set3t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex7set1t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex7set1t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex7set1t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex7set2t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex7set2t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex7set2t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex7set3t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex7set3t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex7set3t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex8set1t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex8set1t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex8set1t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex8set2t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex8set2t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex8set2t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex8set3t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex8set3t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex8set3t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex9set1t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex9set1t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex9set1t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex9set2t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex9set2t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex9set2t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex9set3t1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex9set3t2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='daystage1',
            name='ex9set3t3',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stage1',
            name='begin',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
